#!/usr/bin/env python3
"""Generate the CSS token block and the Vivaldi theme from ONE palette definition.

[ADR-0008]. The palette has to exist in two forms that must agree:

    palettes/<name>.ini                      ← canonical, hand-authored
           ├──→ css/20-palette.css                --tf-* tokens for OUR rules
           └──→ palettes/<name>.theme.json        seeds for Vivaldi's theme engine

Keeping those in sync by hand is the drift hazard ADR-0008 exists to remove, and
it is a nasty one: a disagreement does not error and does not look broken. The
chrome renders in one set of grays and our own rules in another, slightly
different set, which reads as "the theme is a bit off" rather than as a bug with
a location.

Three classes of token, and the generator ENFORCES the split so a value cannot
quietly end up defined twice:

  ALIASED  Vivaldi already supplies it exactly, so css/00-selectors.css aliases
           its --color* variable. Not emitted here. Also gets light/dark
           switching for free, because Vivaldi swaps the seeds itself.
  DERIVED  trimfox documents a FORMULA for it, so 00-selectors.css computes it
           with color-mix() rather than storing it. Not emitted here, and
           putting one in the .ini is an ERROR — that would be a second source
           of truth, which is the whole thing we are preventing.
  EMITTED  everything else: no Vivaldi equivalent close enough in VALUE, and no
           stated formula. These are written to css/20-palette.css.

Usage:
    ./tools/build-palette.py                 regenerate from palettes/grayscale.ini
    ./tools/build-palette.py --check         verify outputs are up to date (CI)
    ./tools/build-palette.py --palette dim   use palettes/dim.ini
"""
import argparse
import configparser
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent

# Supplied by Vivaldi's own variables; aliased in css/00-selectors.css.
ALIASED = {"surface": "--colorBg", "text": "--colorFg"}

# Computed in css/00-selectors.css via color-mix(), from trimfox's own documented
# formula: --tf-line-solid is "the OPAQUE form of --tf-line over --tf-surface".
# The percentage is the alpha trimfox uses for that token.
DERIVED = {
    "line": 18, "line-inactive": 6,
    "line-solid": 18, "line-solid-inactive": 6,
    "highlight": 10,
}

# --tf-* token -> Vivaldi theme seed. Vivaldi derives ~117 --color* properties
# from these five ([ADR-0007]).
THEME_SEEDS = {
    "colorBg": "surface", "colorFg": "text", "colorAccentBg": "accent",
    "colorHighlightBg": "select", "colorWindowBg": "content",
}

# Non-colour theme properties. These encode ethos decisions, not palette values,
# so they live here rather than in the .ini.
THEME_STRUCTURE = {
    "engineVersion": 1, "version": 1,
    # Vivaldi tints its chrome from the page's theme colour by default, which is
    # the single most hostile default to a zero-blue grayscale palette.
    "accentFromPage": False,
    "accentOnWindow": False, "accentSaturationLimit": 0, "preferSystemAccent": False,
    "alpha": 1, "blur": 0, "contrast": 0, "radius": 3,
    "backgroundImage": "", "backgroundPosition": "stretch", "backgroundSource": "",
    "colorPosition": "unified", "transparencyTabBar": False,
    "transparencyTabs": False, "url": "",
}

BANNER = "GENERATED by tools/build-palette.py from {src} — DO NOT EDIT"


# ── the derivation formula, and its regression test ─────────────────────────
def mix(pct, ink, base):
    """Composite `ink` at `pct` over opaque `base` — what color-mix() computes."""
    return tuple(round(i * pct / 100 + b * (1 - pct / 100)) for i, b in zip(ink, base))


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return "#" + "".join(f"{c:02x}" for c in rgb)


def self_test():
    """Assert the CSS formula reproduces trimfox's OWN published values.

    Guards against silently redefining what trimfox means by a separator line.
    Checked against trimfox's ORIGINAL surface (#202020), not trimvaldi's lifted
    one, because these are trimfox's published numbers.
    """
    cases = [
        # (pct, ink,       base,      trimfox's published value, tolerance)
        (18, "#ffffff", "#202020", "#484848", 0),   # dark  --tf-line-solid
        (6,  "#ffffff", "#202020", "#2d2d2d", 0),   # dark  --tf-line-solid-inactive
        # Light uses trimfox's text ink (#111111) where trimfox wrote rgba(0,0,0,…),
        # so a 1/255 difference is expected and accepted.
        (18, "#111111", "#ececec", "#c4c4c4", 1),
        (6,  "#111111", "#ececec", "#dadada", 5),
    ]
    failures = []
    for pct, ink, base, expected, tol in cases:
        got = rgb_to_hex(mix(pct, hex_to_rgb(ink), hex_to_rgb(base)))
        delta = abs(hex_to_rgb(got)[0] - hex_to_rgb(expected)[0])
        mark = "ok" if delta <= tol else "FAIL"
        if delta > tol:
            failures.append(f"{pct}% {ink} over {base}: got {got}, trimfox {expected}")
        print(f"  [{mark:>4}] {pct:>2}% {ink} over {base} -> {got}   "
              f"trimfox {expected}   delta {delta} (tol {tol})")
    return failures


# ── generation ──────────────────────────────────────────────────────────────
def load(path):
    cp = configparser.ConfigParser()
    # Values are colours starting with '#', so inline comments MUST stay off or
    # every hex value would be truncated to empty.
    cp.read_string(path.read_text())
    if not {"dark", "light"} <= set(cp.sections()):
        sys.exit(f"1: {path} needs both a [dark] and a [light] section")

    modes = {m: dict(cp[m]) for m in ("dark", "light")}
    if set(modes["dark"]) != set(modes["light"]):
        only_d = sorted(set(modes["dark"]) - set(modes["light"]))
        only_l = sorted(set(modes["light"]) - set(modes["dark"]))
        sys.exit(f"1: [dark] and [light] must define the same tokens.\n"
                 f"   only in [dark]: {only_d}\n   only in [light]: {only_l}")

    # The split is enforced, not assumed.
    for token in sorted(modes["dark"]):
        if token in DERIVED:
            sys.exit(f"1: '{token}' is DERIVED in css/00-selectors.css via color-mix "
                     f"and must NOT be defined in {path.name} — that would be the "
                     f"second source of truth ADR-0008 exists to prevent.")
    meta = dict(cp["meta"]) if cp.has_section("meta") else {}
    return meta, modes


def emit_css(src, meta, modes):
    emitted = [t for t in sorted(modes["dark"]) if t not in ALIASED]
    skipped = sorted(set(modes["dark"]) & set(ALIASED))
    lines = [
        "/* " + "=" * 74,
        f"   trimvaldi — 20-palette.css   ({meta.get('name', '?')})",
        "   " + BANNER.format(src=src),
        "   " + "-" * 74,
        f"   {meta.get('description', '')}",
        "",
        "   Colour tokens that Vivaldi cannot supply and trimfox states no formula",
        "   for. Everything else is deliberately absent:",
        "",
        f"     ALIASED from Vivaldi ({', '.join(skipped) or 'none'}) — see 00-selectors.css",
        f"     DERIVED via color-mix ({', '.join(sorted(DERIVED))}) — see 00-selectors.css",
        "",
        "   Scoped to Vivaldi's theme classes rather than prefers-color-scheme:",
        "   common.css contains ZERO prefers-color-scheme, and a user's Vivaldi",
        "   theme is independent of the OS appearance, so the media query would",
        "   not track it.",
        "   " + "=" * 74 + " */",
        "",
    ]
    for mode in ("dark", "light"):
        lines.append(f"#browser.theme-{mode} {{")
        width = max(len(t) for t in emitted) + 8
        for token in emitted:
            lines.append(f"  {('--tf-' + token + ':').ljust(width)}{modes[mode][token]};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def emit_theme(src, meta, modes):
    themes = []
    for mode in ("dark", "light"):
        missing = [t for t in THEME_SEEDS.values() if t not in modes[mode]]
        if missing:
            sys.exit(f"1: [{mode}] is missing tokens needed as theme seeds: {missing}")
        themes.append({
            **THEME_STRUCTURE,
            **{seed: modes[mode][token] for seed, token in THEME_SEEDS.items()},
            "id": f"trimvaldi-{mode}",
            "name": f"trimvaldi {mode}",
        })
    return {"_generated": BANNER.format(src=src), "themes": themes}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--palette", default="grayscale")
    ap.add_argument("--check", action="store_true",
                    help="fail if outputs differ from what would be generated")
    args = ap.parse_args()

    src = REPO / "palettes" / f"{args.palette}.ini"
    if not src.exists():
        sys.exit(f"1: no such palette: {src}")

    print(f"Derivation formula vs trimfox's published values:")
    if self_test():
        sys.exit("\n1: the color-mix formula no longer reproduces trimfox. "
                 "Either the formula or trimfox's palette changed — reconcile "
                 "before generating, or the separator lines silently stop "
                 "meaning what trimfox means by them.")

    meta, modes = load(src)
    outputs = {
        REPO / "css" / "20-palette.css": emit_css(src.name, meta, modes),
        REPO / "palettes" / f"{args.palette}.theme.json":
            json.dumps(emit_theme(src.name, meta, modes), indent=2) + "\n",
    }

    stale = []
    for path, content in outputs.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            print(f"\n  unchanged  {path.relative_to(REPO)}")
            continue
        if args.check:
            stale.append(path.relative_to(REPO))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"\n  wrote      {path.relative_to(REPO)}")

    if stale:
        sys.exit(f"\n1: out of date, re-run tools/build-palette.py: "
                 f"{', '.join(str(p) for p in stale)}")


if __name__ == "__main__":
    main()
